### ISSUE TITLE
Merging sources override objects instead of merging

### ISSUE THREAD

**Issue by StummeJ** [Neoteroi/essentials-configuration#10]
Good morning,

We noticed that when you have layered configs, where the environment specific layer only contains modified entries, that objects are not getting merged, but replaced. My expected behavior would be that the layers would be merged, overriding any values that contained further changes.

**appsettings.yaml**
```yaml
logging:
  level: debug
  my_service:
    level: trace
auth:
  token_length: 7
```

**appsettings.prod.yaml**
```yaml
logging:
  my_service:
    level: info
```

**actual builder.buld()**
```py
{
  logger: {
    my_service: {
      level:info
    }
  },
  auth: {
    token_length: 7
  }
}
```

**expected builder.buld()**
```py
{
  logger: {
    level: debug
    my_service: {
      level:info
    }
  },
  auth: {
    token_length: 7
  }
}
```
